"""v1.2

Revision ID: 03ae564e2911
Revises: 3d55f6abe3fe
Create Date: 2021-01-28 13:33:20.241875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ae564e2911'
down_revision = '3d55f6abe3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planinfo', sa.Text(), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('plantime', sa.String(length=20), nullable=True),
    sa.Column('plandata', sa.String(length=20), nullable=True),
    sa.Column('planweek', sa.Integer(), nullable=True),
    sa.Column('planmonth', sa.Integer(), nullable=True),
    sa.Column('planyear', sa.Integer(), nullable=True),
    sa.Column('whetherdone', sa.Integer(), nullable=True),
    sa.Column('whetherimp', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plans')
    # ### end Alembic commands ###
