"""'v1.4'

Revision ID: 12418f67aeab
Revises: 1eadf8e3671d
Create Date: 2021-01-31 14:57:00.958357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12418f67aeab'
down_revision = '1eadf8e3671d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'plandata',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=20),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('plans', 'planmonth',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('本月', '下月', '每月'),
               existing_nullable=True)
    op.alter_column('plans', 'planweek',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('本周', '下周', '每周'),
               existing_nullable=True)
    op.alter_column('plans', 'planyear',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('今年', '每年'),
               existing_nullable=True)
    op.drop_column('plans', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('plans', 'planyear',
               existing_type=sa.Enum('今年', '每年'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('plans', 'planweek',
               existing_type=sa.Enum('本周', '下周', '每周'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('plans', 'planmonth',
               existing_type=sa.Enum('本月', '下月', '每月'),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('plans', 'plandata',
               existing_type=sa.DATE(),
               type_=mysql.VARCHAR(collation='utf8_unicode_ci', length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
