"""'v1.3'

Revision ID: 1eadf8e3671d
Revises: 03ae564e2911
Create Date: 2021-01-31 14:51:19.688968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eadf8e3671d'
down_revision = '03ae564e2911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'test')
    # ### end Alembic commands ###
