"""v1.1

Revision ID: 3d55f6abe3fe
Revises: bcacda94f200
Create Date: 2021-01-24 22:00:00.363466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d55f6abe3fe'
down_revision = 'bcacda94f200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.drop_index('openid', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('openid', 'users', ['openid'], unique=True)
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    # ### end Alembic commands ###
