"""v1.0

Revision ID: aea57a75bcd5
Revises: 
Create Date: 2021-01-17 19:20:50.568793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea57a75bcd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_openid', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=32), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True),
    sa.Column('ctime', mysql.DATETIME(), nullable=True),
    sa.Column('openid', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True),
    sa.Column('extra', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_openid', 'users', ['openid'], unique=False)
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
